In [1]:
import numpy as np

<h1 style="color:green;">Broadcasting</h1>

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = a * b
print(c)

[ 10  40  90 160]


In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 2, 3])
print(a + b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


<h1 style="color:green;">Iterating</h1>

In [4]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print(a)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [5]:
for x in np.nditer(a):
    print(x)

0
5
10
15
20
25
30
35
40
45
50
55
