In [1]:
import numpy as np

<h1 style="color:green;">Create Numpy Array: 1</h1>

In [2]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [3]:
a.reshape(2, 2)

array([[1, 2],
       [3, 4]])

<h1 style="color:green;">Create Numpy Array: 2</h1>

In [4]:
b = np.arange(24)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [5]:
b.reshape(2, 4, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

<h1 style="color:green;">Create Numpy Array: 3</h1>

In [6]:
c = np.zeros(5, dtype=np.int)
print(c)

[0 0 0 0 0]


In [7]:
d = np.ones(5, dtype=np.int)
print(d)

[1 1 1 1 1]


<h1 style="color:green;">Create Numpy Array: 4</h1>

In [8]:
# in between 10 & 20, it creates 5 elements with equal interval.
e = np.linspace(10, 20, 5)
print(e)

[10.  12.5 15.  17.5 20. ]


In [9]:
f = np.linspace(10, 20, 5, endpoint=False, dtype=np.int)
print(f)

[10 12 14 16 18]


<h1 style="color:green;">Create Numpy Array: 5</h1>

In [10]:
g = np.logspace(1.0, 2.0, num=10)
print(g)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [11]:
h = np.logspace(1.0, 2.0, num=10, base=2)
print(h)

[2.         2.16011948 2.33305808 2.5198421  2.72158    2.93946898
 3.1748021  3.42897593 3.70349885 4.        ]
