In [1]:
import numpy as np

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
c = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


<h1 style="color:green;">Slicing: 1</h1>

In [5]:
s = slice(2, 7, 2)
print(a[s])

[2 4 6]


<h1 style="color:green;">Slicing: 2</h1>

In [6]:
print(a[2:7:2])

[2 4 6]


<h1 style="color:green;">Slicing: 3</h1>

In [7]:
print(a[2:])

[2 3 4 5 6 7 8 9]


In [8]:
print(a[2:5])

[2 3 4]


In [9]:
print(b[1:])

[[4 5 6]
 [7 8 9]]


<h1 style="color:green;">Slicing: 4(Integer indexing)</h1>

In [10]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# 0th array's 0th element = 1
# 1st array's 1st element = 5
# 2nd array's 0th element = 7
print(b[[0, 1, 2], [0, 1, 0]])

[1 5 7]


In [12]:
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
# challenge: print corner values i.e 0 2 9 11

print(c[[0, 0, 3, 3], [0, 2, 0, 2]])
print()
# or
row = np.array([[0, 0], [3, 3]])
col = np.array([[0, 2], [0, 2]])
print(c[row, col])

[ 0  2  9 11]

[[ 0  2]
 [ 9 11]]


<h1 style="color:green;">Slicing: 5(Boolean indexing)</h1>

In [14]:
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [15]:
print(c[c>5])

[ 6  7  8  9 10 11]
